import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TemplateOldService {
  form: object;
  const: object;

  constructor() {
    this.form = {
      "@id": "https://repo.staging.metadatacenter.org/templates/bdef01b2-bb90-4f67-9a16-f008d20a5f2b",
      "@type": "https://schema.metadatacenter.org/core/Template",
      "@context": {
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "pav": "http://purl.org/pav/",
        "bibo": "http://purl.org/ontology/bibo/",
        "oslc": "http://open-services.net/ns/core#",
        "schema": "http://schema.org/",
        "schema:name": {
          "@type": "xsd:string"
        },
        "schema:description": {
          "@type": "xsd:string"
        },
        "pav:createdOn": {
          "@type": "xsd:dateTime"
        },
        "pav:createdBy": {
          "@type": "@id"
        },
        "pav:lastUpdatedOn": {
          "@type": "xsd:dateTime"
        },
        "oslc:modifiedBy": {
          "@type": "@id"
        }
      },
      "type": "object",
      "title": "First template template schema",
      "description": "First template template schema generated by the CEDAR Template Editor 2.1.12-SNAPSHOT",
      "_ui": {
        "pages": [],
        "order": [
          "Section One",
          "text field"
        ],
        "propertyLabels": {
          "Section One": "Section One",
          "text field": "text field"
        },
        "propertyDescriptions": {
          "Section One": "Help Text for Section One",
          "text field": "Help Text for text field"
        }
      },
      "properties": {
        "@context": {
          "type": "object",
          "properties": {
            "rdfs": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://www.w3.org/2000/01/rdf-schema#"
              ]
            },
            "xsd": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://www.w3.org/2001/XMLSchema#"
              ]
            },
            "pav": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://purl.org/pav/"
              ]
            },
            "schema": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://schema.org/"
              ]
            },
            "oslc": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://open-services.net/ns/core#"
              ]
            },
            "skos": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://www.w3.org/2004/02/skos/core#"
              ]
            },
            "rdfs:label": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:string"
                  ]
                }
              }
            },
            "schema:isBasedOn": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "@id"
                  ]
                }
              }
            },
            "schema:name": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:string"
                  ]
                }
              }
            },
            "schema:description": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:string"
                  ]
                }
              }
            },
            "pav:createdOn": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:dateTime"
                  ]
                }
              }
            },
            "pav:createdBy": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "@id"
                  ]
                }
              }
            },
            "pav:lastUpdatedOn": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:dateTime"
                  ]
                }
              }
            },
            "oslc:modifiedBy": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "@id"
                  ]
                }
              }
            },
            "skos:notation": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:string"
                  ]
                }
              }
            },
            "text field": {
              "enum": [
                "https://schema.staging.metadatacenter.org/properties/9c04c959-7557-4e4b-a528-a9a39c718b40"
              ]
            }
          },
          "required": [
            "xsd",
            "pav",
            "schema",
            "oslc",
            "schema:isBasedOn",
            "schema:name",
            "schema:description",
            "pav:createdOn",
            "pav:createdBy",
            "pav:lastUpdatedOn",
            "oslc:modifiedBy"
          ],
          "additionalProperties": false
        },
        "@id": {
          "type": "string",
          "format": "uri"
        },
        "@type": {
          "oneOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "format": "uri"
              },
              "uniqueItems": true
            }
          ]
        },
        "schema:isBasedOn": {
          "type": "string",
          "format": "uri"
        },
        "schema:name": {
          "type": "string",
          "minLength": 1
        },
        "schema:description": {
          "type": "string"
        },
        "pav:createdOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "pav:createdBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "pav:lastUpdatedOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "oslc:modifiedBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "Section One": {
          "@type": "https://schema.metadatacenter.org/core/StaticTemplateField",
          "@context": {
            "schema": "http://schema.org/",
            "pav": "http://purl.org/pav/",
            "bibo": "http://purl.org/ontology/bibo/",
            "oslc": "http://open-services.net/ns/core#"
          },
          "type": "object",
          "title": "Section One field schema",
          "description": "Section One field schema generated by the CEDAR Template Editor 2.1.12-SNAPSHOT",
          "_ui": {
            "inputType": "section-break",
            "_content": null
          },
          "pav:createdOn": "2018-11-29T10:28:16-0800",
          "pav:createdBy": "https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8",
          "pav:lastUpdatedOn": "2018-11-29T10:28:16-0800",
          "oslc:modifiedBy": "https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8",
          "schema:schemaVersion": "1.5.0",
          "schema:description": "Help Text for Section One",
          "additionalProperties": false,
          "schema:name": "Section One",
          "skos:prefLabel": "Preferred Label for Section One",
          "@id": "https://repo.staging.metadatacenter.org/template-fields/2b991605-8f12-404f-be8a-42db56a967a7",
          "$schema": "http://json-schema.org/draft-04/schema#"
        },
        "text field": {
          "@type": "https://schema.metadatacenter.org/core/TemplateField",
          "@context": {
            "xsd": "http://www.w3.org/2001/XMLSchema#",
            "pav": "http://purl.org/pav/",
            "bibo": "http://purl.org/ontology/bibo/",
            "oslc": "http://open-services.net/ns/core#",
            "schema": "http://schema.org/",
            "skos": "http://www.w3.org/2004/02/skos/core#",
            "schema:name": {
              "@type": "xsd:string"
            },
            "schema:description": {
              "@type": "xsd:string"
            },
            "skos:prefLabel": {
              "@type": "xsd:string"
            },
            "skos:altLabel": {
              "@type": "xsd:string"
            },
            "pav:createdOn": {
              "@type": "xsd:dateTime"
            },
            "pav:createdBy": {
              "@type": "@id"
            },
            "pav:lastUpdatedOn": {
              "@type": "xsd:dateTime"
            },
            "oslc:modifiedBy": {
              "@type": "@id"
            }
          },
          "type": "object",
          "title": "text field field schema",
          "description": "text field field schema generated by the CEDAR Template Editor 2.1.12-SNAPSHOT",
          "_ui": {
            "inputType": "textfield"
          },
          "_valueConstraints": {
            "requiredValue": false
          },
          "properties": {
            "@type": {
              "oneOf": [
                {
                  "type": "string",
                  "format": "uri"
                },
                {
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "type": "string",
                    "format": "uri"
                  },
                  "uniqueItems": true
                }
              ]
            },
            "@value": {
              "type": [
                "string",
                "null"
              ]
            },
            "rdfs:label": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "@value"
          ],
          "schema:name": "text field",
          "schema:description": "Help Text for text field",
          "pav:createdOn": "2018-11-29T10:28:16-0800",
          "pav:createdBy": "https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8",
          "pav:lastUpdatedOn": "2018-11-29T10:28:16-0800",
          "oslc:modifiedBy": "https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8",
          "schema:schemaVersion": "1.5.0",
          "additionalProperties": false,
          "skos:prefLabel": "preferred label for text field",
          "@id": "https://repo.staging.metadatacenter.org/template-fields/05980e88-ec13-4db4-b0f7-357339e7d538",
          "$schema": "http://json-schema.org/draft-04/schema#"
        }
      },
      "required": [
        "@context",
        "@id",
        "schema:isBasedOn",
        "schema:name",
        "schema:description",
        "pav:createdOn",
        "pav:createdBy",
        "pav:lastUpdatedOn",
        "oslc:modifiedBy",
        "text field"
      ],
      "schema:name": "first template",
      "schema:description": "",
      "pav:createdOn": "2018-11-29T10:28:16-0800",
      "pav:createdBy": "https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8",
      "pav:lastUpdatedOn": "2018-11-29T10:28:16-0800",
      "oslc:modifiedBy": "https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8",
      "schema:schemaVersion": "1.5.0",
      "additionalProperties": false,
      "pav:version": "0.0.1",
      "bibo:status": "bibo:draft",
      "$schema": "http://json-schema.org/draft-04/schema#"
    };

  }

  getTemplate(id, templateId)
  {
    console.log('getTemplate',id, templateId);
    return this.form;
  }
}
