import {Injectable} from '@angular/core';


/* temporary canned data */

const TEMPLATE_DATA = JSON.stringify({
  '@id': 'https://repo.staging.metadatacenter.org/templates/9339cac2-a3a7-49f6-9b4f-73a3fa3a5188',
  '@type': 'https://schema.metadatacenter.org/core/Template',
  '@context': {
    'xsd': 'http://www.w3.org/2001/XMLSchema#',
    'pav': 'http://purl.org/pav/',
    'bibo': 'http://purl.org/ontology/bibo/',
    'oslc': 'http://open-services.net/ns/core#',
    'schema': 'http://schema.org/',
    'schema:name': {
      '@type': 'xsd:string'
    },
    'schema:description': {
      '@type': 'xsd:string'
    },
    'pav:createdOn': {
      '@type': 'xsd:dateTime'
    },
    'pav:createdBy': {
      '@type': '@id'
    },
    'pav:lastUpdatedOn': {
      '@type': 'xsd:dateTime'
    },
    'oslc:modifiedBy': {
      '@type': '@id'
    }
  },
  'type': 'object',
  'title': 'One template template schema',
  'description': 'One template template schema generated by the CEDAR Template Editor 2.2.6',
  '_ui': {
    'pages': [],
    'order': [
      'one field',
      'title'
    ],
    'propertyLabels': {
      'one field': 'one field',
      'title': 'title'
    },
    'propertyDescriptions': {
      'one field': '',
      'title': 'Help Text'
    }
  },
  'properties': {
    '@context': {
      'type': 'object',
      'properties': {
        'rdfs': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://www.w3.org/2000/01/rdf-schema#'
          ]
        },
        'xsd': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://www.w3.org/2001/XMLSchema#'
          ]
        },
        'pav': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://purl.org/pav/'
          ]
        },
        'schema': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://schema.org/'
          ]
        },
        'oslc': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://open-services.net/ns/core#'
          ]
        },
        'skos': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://www.w3.org/2004/02/skos/core#'
          ]
        },
        'rdfs:label': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:string'
              ]
            }
          }
        },
        'schema:isBasedOn': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                '@id'
              ]
            }
          }
        },
        'schema:name': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:string'
              ]
            }
          }
        },
        'schema:description': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:string'
              ]
            }
          }
        },
        'pav:createdOn': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:dateTime'
              ]
            }
          }
        },
        'pav:createdBy': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                '@id'
              ]
            }
          }
        },
        'pav:lastUpdatedOn': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:dateTime'
              ]
            }
          }
        },
        'oslc:modifiedBy': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                '@id'
              ]
            }
          }
        },
        'skos:notation': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:string'
              ]
            }
          }
        },
        'one field': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/f0117f8f-e1c8-4c03-af6c-f96fd8a752fe'
          ]
        },
        'title': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/16031ded-d424-45c7-ae5e-9f5cb0af1821'
          ]
        }
      },
      'required': [
        'xsd',
        'pav',
        'schema',
        'oslc',
        'schema:isBasedOn',
        'schema:name',
        'schema:description',
        'pav:createdOn',
        'pav:createdBy',
        'pav:lastUpdatedOn',
        'oslc:modifiedBy',
        'one field'
      ],
      'additionalProperties': false
    },
    '@id': {
      'type': 'string',
      'format': 'uri'
    },
    '@type': {
      'oneOf': [
        {
          'type': 'string',
          'format': 'uri'
        },
        {
          'type': 'array',
          'minItems': 1,
          'items': {
            'type': 'string',
            'format': 'uri'
          },
          'uniqueItems': true
        }
      ]
    },
    'schema:isBasedOn': {
      'type': 'string',
      'format': 'uri'
    },
    'schema:name': {
      'type': 'string',
      'minLength': 1
    },
    'schema:description': {
      'type': 'string'
    },
    'pav:createdOn': {
      'type': [
        'string',
        'null'
      ],
      'format': 'date-time'
    },
    'pav:createdBy': {
      'type': [
        'string',
        'null'
      ],
      'format': 'uri'
    },
    'pav:lastUpdatedOn': {
      'type': [
        'string',
        'null'
      ],
      'format': 'date-time'
    },
    'oslc:modifiedBy': {
      'type': [
        'string',
        'null'
      ],
      'format': 'uri'
    },
    'one field': {
      'type': 'array',
      'minItems': 1,
      'items': {
        'type': 'object',
        '@id': 'https://repo.staging.metadatacenter.org/template-elements/c9492fd2-8889-4c86-949a-005bd8d59284',
        '@type': 'https://schema.metadatacenter.org/core/TemplateElement',
        '@context': {
          'xsd': 'http://www.w3.org/2001/XMLSchema#',
          'pav': 'http://purl.org/pav/',
          'bibo': 'http://purl.org/ontology/bibo/',
          'oslc': 'http://open-services.net/ns/core#',
          'schema': 'http://schema.org/',
          'schema:name': {
            '@type': 'xsd:string'
          },
          'schema:description': {
            '@type': 'xsd:string'
          },
          'pav:createdOn': {
            '@type': 'xsd:dateTime'
          },
          'pav:createdBy': {
            '@type': '@id'
          },
          'pav:lastUpdatedOn': {
            '@type': 'xsd:dateTime'
          },
          'oslc:modifiedBy': {
            '@type': '@id'
          }
        },
        'title': 'one field field schema',
        'description': 'one field field schema generated by the CEDAR Template Editor 2.2.6',
        '_ui': {
          'order': [
            'field'
          ],
          'propertyLabels': {
            'field': 'field'
          },
          'propertyDescriptions': {
            'field': 'Help Text'
          }
        },
        'properties': {
          '@context': {
            'type': 'object',
            'properties': {
              'field': {
                'enum': [
                  'https://schema.staging.metadatacenter.org/properties/8a1c35cd-c2dc-4622-9f9a-36cf1b8e4560'
                ]
              }
            },
            'additionalProperties': false,
            'required': [
              'field'
            ]
          },
          '@id': {
            'type': 'string',
            'format': 'uri'
          },
          '@type': {
            'oneOf': [
              {
                'type': 'string',
                'format': 'uri'
              },
              {
                'type': 'array',
                'minItems': 1,
                'items': {
                  'type': 'string',
                  'format': 'uri'
                },
                'uniqueItems': true
              }
            ]
          },
          'field': {
            'type': 'array',
            'minItems': 1,
            'items': {
              'type': 'object',
              '@id': 'https://repo.staging.metadatacenter.org/template-fields/2426e170-115c-414f-888a-54c021499487',
              '@type': 'https://schema.metadatacenter.org/core/TemplateField',
              '@context': {
                'xsd': 'http://www.w3.org/2001/XMLSchema#',
                'pav': 'http://purl.org/pav/',
                'bibo': 'http://purl.org/ontology/bibo/',
                'oslc': 'http://open-services.net/ns/core#',
                'schema': 'http://schema.org/',
                'skos': 'http://www.w3.org/2004/02/skos/core#',
                'schema:name': {
                  '@type': 'xsd:string'
                },
                'schema:description': {
                  '@type': 'xsd:string'
                },
                'skos:prefLabel': {
                  '@type': 'xsd:string'
                },
                'skos:altLabel': {
                  '@type': 'xsd:string'
                },
                'pav:createdOn': {
                  '@type': 'xsd:dateTime'
                },
                'pav:createdBy': {
                  '@type': '@id'
                },
                'pav:lastUpdatedOn': {
                  '@type': 'xsd:dateTime'
                },
                'oslc:modifiedBy': {
                  '@type': '@id'
                }
              },
              'title': 'field field schema',
              'description': 'field field schema generated by the CEDAR Template Editor 2.2.6',
              '_ui': {
                'inputType': 'textfield'
              },
              '_valueConstraints': {
                'requiredValue': false
              },
              'properties': {
                '@type': {
                  'oneOf': [
                    {
                      'type': 'string',
                      'format': 'uri'
                    },
                    {
                      'type': 'array',
                      'minItems': 1,
                      'items': {
                        'type': 'string',
                        'format': 'uri'
                      },
                      'uniqueItems': true
                    }
                  ]
                },
                '@value': {
                  'type': [
                    'string',
                    'null'
                  ]
                },
                'rdfs:label': {
                  'type': [
                    'string',
                    'null'
                  ]
                }
              },
              'required': [
                '@value'
              ],
              'additionalProperties': false,
              'pav:createdOn': '2019-01-28T14:40:59-0800',
              'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
              'pav:lastUpdatedOn': '2019-01-28T14:40:59-0800',
              'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
              'schema:schemaVersion': '1.5.0',
              'schema:name': 'field',
              'schema:description': 'Help Text',
              '$schema': 'http://json-schema.org/draft-04/schema#'
            }
          }
        },
        'required': [
          '@context',
          '@id',
          'field'
        ],
        'additionalProperties': false,
        'pav:createdOn': '2019-01-28T14:41:45-0800',
        'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'pav:lastUpdatedOn': '2019-01-28T14:41:45-0800',
        'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'schema:schemaVersion': '1.5.0',
        'schema:name': 'one field',
        'schema:description': '',
        'pav:version': '0.0.1',
        'bibo:status': 'bibo:draft',
        '$schema': 'http://json-schema.org/draft-04/schema#'
      }
    },
    'title': {
      'type': 'array',
      'minItems': 1,
      'items': {
        'type': 'object',
        '@type': 'https://schema.metadatacenter.org/core/TemplateField',
        '@context': {
          'xsd': 'http://www.w3.org/2001/XMLSchema#',
          'pav': 'http://purl.org/pav/',
          'bibo': 'http://purl.org/ontology/bibo/',
          'oslc': 'http://open-services.net/ns/core#',
          'schema': 'http://schema.org/',
          'skos': 'http://www.w3.org/2004/02/skos/core#',
          'schema:name': {
            '@type': 'xsd:string'
          },
          'schema:description': {
            '@type': 'xsd:string'
          },
          'skos:prefLabel': {
            '@type': 'xsd:string'
          },
          'skos:altLabel': {
            '@type': 'xsd:string'
          },
          'pav:createdOn': {
            '@type': 'xsd:dateTime'
          },
          'pav:createdBy': {
            '@type': '@id'
          },
          'pav:lastUpdatedOn': {
            '@type': 'xsd:dateTime'
          },
          'oslc:modifiedBy': {
            '@type': '@id'
          }
        },
        'title': 'title field schema',
        'description': 'title field schema generated by the CEDAR Template Editor 2.2.6',
        '_ui': {
          'inputType': 'textfield'
        },
        '_valueConstraints': {
          'requiredValue': false
        },
        'properties': {
          '@type': {
            'oneOf': [
              {
                'type': 'string',
                'format': 'uri'
              },
              {
                'type': 'array',
                'minItems': 1,
                'items': {
                  'type': 'string',
                  'format': 'uri'
                },
                'uniqueItems': true
              }
            ]
          },
          '@value': {
            'type': [
              'string',
              'null'
            ]
          },
          'rdfs:label': {
            'type': [
              'string',
              'null'
            ]
          }
        },
        'required': [
          '@value'
        ],
        'additionalProperties': false,
        'pav:createdOn': '2019-01-28T14:41:45-0800',
        'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'pav:lastUpdatedOn': '2019-01-28T14:41:45-0800',
        'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'schema:schemaVersion': '1.5.0',
        'schema:name': 'title',
        'schema:description': 'Help Text',
        '@id': 'https://repo.staging.metadatacenter.org/template-fields/744026f6-66ed-4541-8bfd-fea309d7ad81',
        '$schema': 'http://json-schema.org/draft-04/schema#'
      }
    }
  },
  'required': [
    '@context',
    '@id',
    'schema:isBasedOn',
    'schema:name',
    'schema:description',
    'pav:createdOn',
    'pav:createdBy',
    'pav:lastUpdatedOn',
    'oslc:modifiedBy',
    'one field',
    'title'
  ],
  'schema:name': 'one template',
  'schema:description': '',
  'pav:createdOn': '2019-01-28T14:41:34-0800',
  'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
  'pav:lastUpdatedOn': '2019-01-28T14:41:45-0800',
  'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
  'schema:schemaVersion': '1.5.0',
  'additionalProperties': false,
  'pav:version': '0.0.1',
  'bibo:status': 'bibo:draft',
  '$schema': 'http://json-schema.org/draft-04/schema#'
});
const MODEL_DATA = JSON.stringify({
  '@context': {
    'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
    'xsd': 'http://www.w3.org/2001/XMLSchema#',
    'pav': 'http://purl.org/pav/',
    'schema': 'http://schema.org/',
    'oslc': 'http://open-services.net/ns/core#',
    'skos': 'http://www.w3.org/2004/02/skos/core#',
    'rdfs:label': {
      '@type': 'xsd:string'
    },
    'schema:isBasedOn': {
      '@type': '@id'
    },
    'schema:name': {
      '@type': 'xsd:string'
    },
    'schema:description': {
      '@type': 'xsd:string'
    },
    'pav:createdOn': {
      '@type': 'xsd:dateTime'
    },
    'pav:createdBy': {
      '@type': '@id'
    },
    'pav:lastUpdatedOn': {
      '@type': 'xsd:dateTime'
    },
    'oslc:modifiedBy': {
      '@type': '@id'
    },
    'skos:notation': {
      '@type': 'xsd:string'
    },
    'one field': 'https://schema.staging.metadatacenter.org/properties/f0117f8f-e1c8-4c03-af6c-f96fd8a752fe',
    'title': 'https://schema.staging.metadatacenter.org/properties/16031ded-d424-45c7-ae5e-9f5cb0af1821'
  },
  'one field': [
    {
      '@context': {
        'field': 'https://schema.staging.metadatacenter.org/properties/8a1c35cd-c2dc-4622-9f9a-36cf1b8e4560'
      },
      'field': [
        {
          '@value': 'one'
        },
        {
          '@value': 'two'
        }
      ],
      '@id': 'https://repo.staging.metadatacenter.org/template-element-instances/1995b77c-6da7-4589-b836-826b1469a17e'
    },
    {
      '@context': {
        'field': 'https://schema.staging.metadatacenter.org/properties/8a1c35cd-c2dc-4622-9f9a-36cf1b8e4560'
      },
      'field': [
        {
          '@value': 'three'
        },
        {
          '@value': 'four'
        }
      ],
      '@id': 'https://repo.staging.metadatacenter.org/template-element-instances/84f21ecb-ab38-45e1-905c-5a9ecb2384c7'
    }
  ],
  'title': [
    {
      '@value': 'five'
    },
    {
      '@value': 'six'
    }
  ],
  'schema:isBasedOn': 'https://repo.staging.metadatacenter.org/templates/9339cac2-a3a7-49f6-9b4f-73a3fa3a5188',
  'schema:name': 'one template metadata',
  'schema:description': '',
  'pav:createdOn': '2019-01-28T16:34:51-0800',
  'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
  'pav:lastUpdatedOn': '2019-01-28T16:40:27-0800',
  'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
  '@id': 'https://repo.staging.metadatacenter.org/template-instances/9308a4f7-e34f-4602-a5ee-2136547f6184'
});
const TEMPLATE_DATA1 = JSON.stringify({
  '@id': 'https://repo.staging.metadatacenter.org/templates/7ed749c4-7ecc-482b-b7c8-a9c5368c004b',
  '@type': 'https://schema.metadatacenter.org/core/Template',
  '@context': {
    'xsd': 'http://www.w3.org/2001/XMLSchema#',
    'pav': 'http://purl.org/pav/',
    'bibo': 'http://purl.org/ontology/bibo/',
    'oslc': 'http://open-services.net/ns/core#',
    'schema': 'http://schema.org/',
    'schema:name': {
      '@type': 'xsd:string'
    },
    'schema:description': {
      '@type': 'xsd:string'
    },
    'pav:createdOn': {
      '@type': 'xsd:dateTime'
    },
    'pav:createdBy': {
      '@type': '@id'
    },
    'pav:lastUpdatedOn': {
      '@type': 'xsd:dateTime'
    },
    'oslc:modifiedBy': {
      '@type': '@id'
    }
  },
  'type': 'object',
  'title': 'Fieldtypes template schema',
  'description': 'Fieldtypes template schema generated by the CEDAR Template Editor 2.2.6',
  '_ui': {
    'pages': [],
    'order': [
      'text',
      'date',
      'email',
      'number',
      'link',
      'paragraph',
      'radio',
      'checkbox',
      'list',
      'phone',
      'attribute value'
    ],
    'propertyLabels': {
      'text': 'text',
      'date': 'date',
      'email': 'email',
      'number': 'number',
      'link': 'link',
      'paragraph': 'paragraph',
      'radio': 'radio',
      'checkbox': 'checkbox',
      'phone': 'phone',
      'attribute value': 'attribute value',
      'list': 'list'
    },
    'propertyDescriptions': {
      'text': 'Help Text',
      'date': 'Help Text',
      'email': 'Help Text',
      'number': 'Help Text',
      'link': 'Help Text',
      'paragraph': 'Help Text',
      'radio': 'Help Text',
      'checkbox': 'Help Text',
      'phone': 'Help Text',
      'attribute value': 'Help Text',
      'list': 'Help Text'
    }
  },
  'properties': {
    '@context': {
      'type': 'object',
      'properties': {
        'rdfs': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://www.w3.org/2000/01/rdf-schema#'
          ]
        },
        'xsd': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://www.w3.org/2001/XMLSchema#'
          ]
        },
        'pav': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://purl.org/pav/'
          ]
        },
        'schema': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://schema.org/'
          ]
        },
        'oslc': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://open-services.net/ns/core#'
          ]
        },
        'skos': {
          'type': 'string',
          'format': 'uri',
          'enum': [
            'http://www.w3.org/2004/02/skos/core#'
          ]
        },
        'rdfs:label': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:string'
              ]
            }
          }
        },
        'schema:isBasedOn': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                '@id'
              ]
            }
          }
        },
        'schema:name': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:string'
              ]
            }
          }
        },
        'schema:description': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:string'
              ]
            }
          }
        },
        'pav:createdOn': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:dateTime'
              ]
            }
          }
        },
        'pav:createdBy': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                '@id'
              ]
            }
          }
        },
        'pav:lastUpdatedOn': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:dateTime'
              ]
            }
          }
        },
        'oslc:modifiedBy': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                '@id'
              ]
            }
          }
        },
        'skos:notation': {
          'type': 'object',
          'properties': {
            '@type': {
              'type': 'string',
              'enum': [
                'xsd:string'
              ]
            }
          }
        },
        'text': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/382f3f49-bd0b-4dce-bdf5-c1c61306a639'
          ]
        },
        'date': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/8ec1d134-2fac-4469-a12a-742f3689a821'
          ]
        },
        'email': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/ad59e2a4-7b9a-4bb1-a4f1-e19928dc7587'
          ]
        },
        'number': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/360c3f74-ab05-4f54-a2c9-fe7e3431d050'
          ]
        },
        'link': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/1b049d85-956c-4913-9acb-f6a8046bd2af'
          ]
        },
        'paragraph': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/1761d919-d82e-48e5-9b22-cee13b36c0cc'
          ]
        },
        'radio': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/1e3cff2b-ab73-45c7-8e33-95102da99eeb'
          ]
        },
        'checkbox': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/dfbff46a-5075-4e0c-99aa-d328197e18a7'
          ]
        },
        'phone': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/699223a8-87d1-4942-bd22-64a18e051430'
          ]
        },
        'attribute value': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/612b0a81-9edb-4f6c-926d-45af85b8119b'
          ]
        },
        'list': {
          'enum': [
            'https://schema.staging.metadatacenter.org/properties/5e5aa219-787d-41a7-b0bf-e360441ec00a'
          ]
        }
      },
      'required': [
        'xsd',
        'pav',
        'schema',
        'oslc',
        'schema:isBasedOn',
        'schema:name',
        'schema:description',
        'pav:createdOn',
        'pav:createdBy',
        'pav:lastUpdatedOn',
        'oslc:modifiedBy'
      ],
      'additionalProperties': {
        'type': 'string',
        'format': 'uri'
      }
    },
    '@id': {
      'type': 'string',
      'format': 'uri'
    },
    '@type': {
      'oneOf': [
        {
          'type': 'string',
          'format': 'uri'
        },
        {
          'type': 'array',
          'minItems': 1,
          'items': {
            'type': 'string',
            'format': 'uri'
          },
          'uniqueItems': true
        }
      ]
    },
    'schema:isBasedOn': {
      'type': 'string',
      'format': 'uri'
    },
    'schema:name': {
      'type': 'string',
      'minLength': 1
    },
    'schema:description': {
      'type': 'string'
    },
    'pav:createdOn': {
      'type': [
        'string',
        'null'
      ],
      'format': 'date-time'
    },
    'pav:createdBy': {
      'type': [
        'string',
        'null'
      ],
      'format': 'uri'
    },
    'pav:lastUpdatedOn': {
      'type': [
        'string',
        'null'
      ],
      'format': 'date-time'
    },
    'oslc:modifiedBy': {
      'type': [
        'string',
        'null'
      ],
      'format': 'uri'
    },
    'text': {
      'type': 'array',
      'minItems': 1,
      'items': {
        'type': 'object',
        '@type': 'https://schema.metadatacenter.org/core/TemplateField',
        '@context': {
          'xsd': 'http://www.w3.org/2001/XMLSchema#',
          'pav': 'http://purl.org/pav/',
          'bibo': 'http://purl.org/ontology/bibo/',
          'oslc': 'http://open-services.net/ns/core#',
          'schema': 'http://schema.org/',
          'skos': 'http://www.w3.org/2004/02/skos/core#',
          'schema:name': {
            '@type': 'xsd:string'
          },
          'schema:description': {
            '@type': 'xsd:string'
          },
          'skos:prefLabel': {
            '@type': 'xsd:string'
          },
          'skos:altLabel': {
            '@type': 'xsd:string'
          },
          'pav:createdOn': {
            '@type': 'xsd:dateTime'
          },
          'pav:createdBy': {
            '@type': '@id'
          },
          'pav:lastUpdatedOn': {
            '@type': 'xsd:dateTime'
          },
          'oslc:modifiedBy': {
            '@type': '@id'
          }
        },
        'title': 'text field schema',
        'description': 'text field schema generated by the CEDAR Template Editor 2.2.6',
        '_ui': {
          'inputType': 'textfield'
        },
        '_valueConstraints': {
          'requiredValue': false
        },
        'properties': {
          '@type': {
            'oneOf': [
              {
                'type': 'string',
                'format': 'uri'
              },
              {
                'type': 'array',
                'minItems': 1,
                'items': {
                  'type': 'string',
                  'format': 'uri'
                },
                'uniqueItems': true
              }
            ]
          },
          '@value': {
            'type': [
              'string',
              'null'
            ]
          },
          'rdfs:label': {
            'type': [
              'string',
              'null'
            ]
          }
        },
        'required': [
          '@value'
        ],
        'additionalProperties': false,
        'pav:createdOn': '2019-01-30T15:43:56-0800',
        'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
        'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'schema:schemaVersion': '1.5.0',
        'schema:name': 'text',
        'schema:description': 'Help Text',
        '@id': 'https://repo.staging.metadatacenter.org/template-fields/90463960-2e8c-43dc-88e2-2e8bb5cfaa70',
        '$schema': 'http://json-schema.org/draft-04/schema#'
      }
    },
    'date': {
      'type': 'array',
      'minItems': 1,
      'items': {
        'type': 'object',
        '@type': 'https://schema.metadatacenter.org/core/TemplateField',
        '@context': {
          'xsd': 'http://www.w3.org/2001/XMLSchema#',
          'pav': 'http://purl.org/pav/',
          'bibo': 'http://purl.org/ontology/bibo/',
          'oslc': 'http://open-services.net/ns/core#',
          'schema': 'http://schema.org/',
          'skos': 'http://www.w3.org/2004/02/skos/core#',
          'schema:name': {
            '@type': 'xsd:string'
          },
          'schema:description': {
            '@type': 'xsd:string'
          },
          'skos:prefLabel': {
            '@type': 'xsd:string'
          },
          'skos:altLabel': {
            '@type': 'xsd:string'
          },
          'pav:createdOn': {
            '@type': 'xsd:dateTime'
          },
          'pav:createdBy': {
            '@type': '@id'
          },
          'pav:lastUpdatedOn': {
            '@type': 'xsd:dateTime'
          },
          'oslc:modifiedBy': {
            '@type': '@id'
          }
        },
        'title': 'date field schema',
        'description': 'date field schema generated by the CEDAR Template Editor 2.2.6',
        '_ui': {
          'inputType': 'date'
        },
        '_valueConstraints': {
          'requiredValue': true
        },
        'properties': {
          '@value': {
            'type': [
              'string',
              'null'
            ]
          },
          'rdfs:label': {
            'type': [
              'string',
              'null'
            ]
          },
          '@type': {
            'type': 'string',
            'format': 'uri'
          }
        },
        'required': [
          '@value',
          '@type'
        ],
        'additionalProperties': false,
        'pav:createdOn': '2019-01-30T15:43:56-0800',
        'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
        'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'schema:schemaVersion': '1.5.0',
        'schema:name': 'date',
        'schema:description': 'Help Text',
        '@id': 'https://repo.staging.metadatacenter.org/template-fields/452f9559-46c3-42cb-8ec2-4f328325fa4b',
        '$schema': 'http://json-schema.org/draft-04/schema#'
      }
    },
    'email': {
      '@type': 'https://schema.metadatacenter.org/core/TemplateField',
      '@context': {
        'xsd': 'http://www.w3.org/2001/XMLSchema#',
        'pav': 'http://purl.org/pav/',
        'bibo': 'http://purl.org/ontology/bibo/',
        'oslc': 'http://open-services.net/ns/core#',
        'schema': 'http://schema.org/',
        'skos': 'http://www.w3.org/2004/02/skos/core#',
        'schema:name': {
          '@type': 'xsd:string'
        },
        'schema:description': {
          '@type': 'xsd:string'
        },
        'skos:prefLabel': {
          '@type': 'xsd:string'
        },
        'skos:altLabel': {
          '@type': 'xsd:string'
        },
        'pav:createdOn': {
          '@type': 'xsd:dateTime'
        },
        'pav:createdBy': {
          '@type': '@id'
        },
        'pav:lastUpdatedOn': {
          '@type': 'xsd:dateTime'
        },
        'oslc:modifiedBy': {
          '@type': '@id'
        }
      },
      'type': 'object',
      'title': 'email field schema',
      'description': 'email field schema generated by the CEDAR Template Editor 2.2.6',
      '_ui': {
        'inputType': 'email'
      },
      '_valueConstraints': {
        'requiredValue': false
      },
      'properties': {
        '@type': {
          'oneOf': [
            {
              'type': 'string',
              'format': 'uri'
            },
            {
              'type': 'array',
              'minItems': 1,
              'items': {
                'type': 'string',
                'format': 'uri'
              },
              'uniqueItems': true
            }
          ]
        },
        '@value': {
          'type': [
            'string',
            'null'
          ]
        },
        'rdfs:label': {
          'type': [
            'string',
            'null'
          ]
        }
      },
      'required': [
        '@value'
      ],
      'schema:name': 'email',
      'schema:description': 'Help Text',
      'pav:createdOn': '2019-01-30T15:43:56-0800',
      'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
      'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'schema:schemaVersion': '1.5.0',
      'additionalProperties': false,
      '@id': 'https://repo.staging.metadatacenter.org/template-fields/8bc3845f-0f0d-45e4-afb3-59d258eff27a',
      '$schema': 'http://json-schema.org/draft-04/schema#'
    },
    'number': {
      '@type': 'https://schema.metadatacenter.org/core/TemplateField',
      '@context': {
        'xsd': 'http://www.w3.org/2001/XMLSchema#',
        'pav': 'http://purl.org/pav/',
        'bibo': 'http://purl.org/ontology/bibo/',
        'oslc': 'http://open-services.net/ns/core#',
        'schema': 'http://schema.org/',
        'skos': 'http://www.w3.org/2004/02/skos/core#',
        'schema:name': {
          '@type': 'xsd:string'
        },
        'schema:description': {
          '@type': 'xsd:string'
        },
        'skos:prefLabel': {
          '@type': 'xsd:string'
        },
        'skos:altLabel': {
          '@type': 'xsd:string'
        },
        'pav:createdOn': {
          '@type': 'xsd:dateTime'
        },
        'pav:createdBy': {
          '@type': '@id'
        },
        'pav:lastUpdatedOn': {
          '@type': 'xsd:dateTime'
        },
        'oslc:modifiedBy': {
          '@type': '@id'
        }
      },
      'type': 'object',
      'title': 'number field schema',
      'description': 'number field schema generated by the CEDAR Template Editor 2.2.6',
      '_ui': {
        'inputType': 'numeric'
      },
      '_valueConstraints': {
        'requiredValue': false,
        'numberType': 'xsd:decimal'
      },
      'properties': {
        '@value': {
          'type': [
            'string',
            'null'
          ]
        },
        'rdfs:label': {
          'type': [
            'string',
            'null'
          ]
        },
        '@type': {
          'type': 'string',
          'format': 'uri'
        }
      },
      'required': [
        '@value',
        '@type'
      ],
      'schema:name': 'number',
      'schema:description': 'Help Text',
      'pav:createdOn': '2019-01-30T15:43:56-0800',
      'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
      'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'schema:schemaVersion': '1.5.0',
      'additionalProperties': false,
      '@id': 'https://repo.staging.metadatacenter.org/template-fields/dee57482-d10d-4f8a-a4d2-d9a764d33d36',
      '$schema': 'http://json-schema.org/draft-04/schema#'
    },
    'link': {
      '@type': 'https://schema.metadatacenter.org/core/TemplateField',
      '@context': {
        'xsd': 'http://www.w3.org/2001/XMLSchema#',
        'pav': 'http://purl.org/pav/',
        'bibo': 'http://purl.org/ontology/bibo/',
        'oslc': 'http://open-services.net/ns/core#',
        'schema': 'http://schema.org/',
        'skos': 'http://www.w3.org/2004/02/skos/core#',
        'schema:name': {
          '@type': 'xsd:string'
        },
        'schema:description': {
          '@type': 'xsd:string'
        },
        'skos:prefLabel': {
          '@type': 'xsd:string'
        },
        'skos:altLabel': {
          '@type': 'xsd:string'
        },
        'pav:createdOn': {
          '@type': 'xsd:dateTime'
        },
        'pav:createdBy': {
          '@type': '@id'
        },
        'pav:lastUpdatedOn': {
          '@type': 'xsd:dateTime'
        },
        'oslc:modifiedBy': {
          '@type': '@id'
        }
      },
      'type': 'object',
      'title': 'link field schema',
      'description': 'link field schema generated by the CEDAR Template Editor 2.2.6',
      '_ui': {
        'inputType': 'link'
      },
      '_valueConstraints': {
        'requiredValue': false
      },
      'properties': {
        '@type': {
          'oneOf': [
            {
              'type': 'string',
              'format': 'uri'
            },
            {
              'type': 'array',
              'minItems': 1,
              'items': {
                'type': 'string',
                'format': 'uri'
              },
              'uniqueItems': true
            }
          ]
        },
        'rdfs:label': {
          'type': [
            'string',
            'null'
          ]
        },
        '@id': {
          'type': 'string',
          'format': 'uri'
        }
      },
      'schema:name': 'link',
      'schema:description': 'Help Text',
      'pav:createdOn': '2019-01-30T15:43:56-0800',
      'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
      'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'schema:schemaVersion': '1.5.0',
      'additionalProperties': false,
      '@id': 'https://repo.staging.metadatacenter.org/template-fields/77f6ac19-7d67-408e-98e0-6460dd949712',
      '$schema': 'http://json-schema.org/draft-04/schema#'
    },
    'paragraph': {
      '@type': 'https://schema.metadatacenter.org/core/TemplateField',
      '@context': {
        'xsd': 'http://www.w3.org/2001/XMLSchema#',
        'pav': 'http://purl.org/pav/',
        'bibo': 'http://purl.org/ontology/bibo/',
        'oslc': 'http://open-services.net/ns/core#',
        'schema': 'http://schema.org/',
        'skos': 'http://www.w3.org/2004/02/skos/core#',
        'schema:name': {
          '@type': 'xsd:string'
        },
        'schema:description': {
          '@type': 'xsd:string'
        },
        'skos:prefLabel': {
          '@type': 'xsd:string'
        },
        'skos:altLabel': {
          '@type': 'xsd:string'
        },
        'pav:createdOn': {
          '@type': 'xsd:dateTime'
        },
        'pav:createdBy': {
          '@type': '@id'
        },
        'pav:lastUpdatedOn': {
          '@type': 'xsd:dateTime'
        },
        'oslc:modifiedBy': {
          '@type': '@id'
        }
      },
      'type': 'object',
      'title': 'paragraph field schema',
      'description': 'paragraph field schema generated by the CEDAR Template Editor 2.2.6',
      '_ui': {
        'inputType': 'textarea'
      },
      '_valueConstraints': {
        'requiredValue': false
      },
      'properties': {
        '@type': {
          'oneOf': [
            {
              'type': 'string',
              'format': 'uri'
            },
            {
              'type': 'array',
              'minItems': 1,
              'items': {
                'type': 'string',
                'format': 'uri'
              },
              'uniqueItems': true
            }
          ]
        },
        '@value': {
          'type': [
            'string',
            'null'
          ]
        },
        'rdfs:label': {
          'type': [
            'string',
            'null'
          ]
        }
      },
      'required': [
        '@value'
      ],
      'schema:name': 'paragraph',
      'schema:description': 'Help Text',
      'pav:createdOn': '2019-01-30T15:43:56-0800',
      'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
      'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'schema:schemaVersion': '1.5.0',
      'additionalProperties': false,
      '@id': 'https://repo.staging.metadatacenter.org/template-fields/f576b1d0-5af1-4eab-83e2-8e688455f5d4',
      '$schema': 'http://json-schema.org/draft-04/schema#'
    },
    'radio': {
      '@type': 'https://schema.metadatacenter.org/core/TemplateField',
      '@context': {
        'xsd': 'http://www.w3.org/2001/XMLSchema#',
        'pav': 'http://purl.org/pav/',
        'bibo': 'http://purl.org/ontology/bibo/',
        'oslc': 'http://open-services.net/ns/core#',
        'schema': 'http://schema.org/',
        'skos': 'http://www.w3.org/2004/02/skos/core#',
        'schema:name': {
          '@type': 'xsd:string'
        },
        'schema:description': {
          '@type': 'xsd:string'
        },
        'skos:prefLabel': {
          '@type': 'xsd:string'
        },
        'skos:altLabel': {
          '@type': 'xsd:string'
        },
        'pav:createdOn': {
          '@type': 'xsd:dateTime'
        },
        'pav:createdBy': {
          '@type': '@id'
        },
        'pav:lastUpdatedOn': {
          '@type': 'xsd:dateTime'
        },
        'oslc:modifiedBy': {
          '@type': '@id'
        }
      },
      'type': 'object',
      'title': 'radio field schema',
      'description': 'radio field schema generated by the CEDAR Template Editor 2.2.6',
      '_ui': {
        'inputType': 'radio'
      },
      '_valueConstraints': {
        'requiredValue': false,
        'multipleChoice': false,
        'literals': [
          {
            'label': 'Untitled-0'
          },
          {
            'label': 'Untitled-1'
          }
        ]
      },
      'properties': {
        '@type': {
          'oneOf': [
            {
              'type': 'string',
              'format': 'uri'
            },
            {
              'type': 'array',
              'minItems': 1,
              'items': {
                'type': 'string',
                'format': 'uri'
              },
              'uniqueItems': true
            }
          ]
        },
        '@value': {
          'type': [
            'string',
            'null'
          ]
        },
        'rdfs:label': {
          'type': [
            'string',
            'null'
          ]
        }
      },
      'required': [
        '@value'
      ],
      'schema:name': 'radio',
      'schema:description': 'Help Text',
      'pav:createdOn': '2019-01-30T15:43:56-0800',
      'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
      'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'schema:schemaVersion': '1.5.0',
      'additionalProperties': false,
      '@id': 'https://repo.staging.metadatacenter.org/template-fields/931e9571-72a5-4f9a-ae2b-38b4b5128b13',
      '$schema': 'http://json-schema.org/draft-04/schema#'
    },
    'checkbox': {
      'type': 'array',
      'minItems': 1,
      'items': {
        'type': 'object',
        '@type': 'https://schema.metadatacenter.org/core/TemplateField',
        '@context': {
          'xsd': 'http://www.w3.org/2001/XMLSchema#',
          'pav': 'http://purl.org/pav/',
          'bibo': 'http://purl.org/ontology/bibo/',
          'oslc': 'http://open-services.net/ns/core#',
          'schema': 'http://schema.org/',
          'skos': 'http://www.w3.org/2004/02/skos/core#',
          'schema:name': {
            '@type': 'xsd:string'
          },
          'schema:description': {
            '@type': 'xsd:string'
          },
          'skos:prefLabel': {
            '@type': 'xsd:string'
          },
          'skos:altLabel': {
            '@type': 'xsd:string'
          },
          'pav:createdOn': {
            '@type': 'xsd:dateTime'
          },
          'pav:createdBy': {
            '@type': '@id'
          },
          'pav:lastUpdatedOn': {
            '@type': 'xsd:dateTime'
          },
          'oslc:modifiedBy': {
            '@type': '@id'
          }
        },
        'title': 'checkbox field schema',
        'description': 'checkbox field schema generated by the CEDAR Template Editor 2.2.6',
        '_ui': {
          'inputType': 'checkbox'
        },
        '_valueConstraints': {
          'requiredValue': false,
          'multipleChoice': true,
          'literals': [
            {
              'label': 'Untitled-0'
            },
            {
              'label': 'Untitled-1'
            }
          ]
        },
        'properties': {
          '@type': {
            'oneOf': [
              {
                'type': 'string',
                'format': 'uri'
              },
              {
                'type': 'array',
                'minItems': 1,
                'items': {
                  'type': 'string',
                  'format': 'uri'
                },
                'uniqueItems': true
              }
            ]
          },
          '@value': {
            'type': [
              'string',
              'null'
            ]
          },
          'rdfs:label': {
            'type': [
              'string',
              'null'
            ]
          }
        },
        'required': [
          '@value'
        ],
        'additionalProperties': false,
        'pav:createdOn': '2019-01-30T15:43:56-0800',
        'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
        'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'schema:schemaVersion': '1.5.0',
        'schema:name': 'checkbox',
        'schema:description': 'Help Text',
        '@id': 'https://repo.staging.metadatacenter.org/template-fields/5fc851f5-1c5b-4e5d-8764-996c3089d176',
        '$schema': 'http://json-schema.org/draft-04/schema#'
      }
    },
    'phone': {
      '@type': 'https://schema.metadatacenter.org/core/TemplateField',
      '@context': {
        'xsd': 'http://www.w3.org/2001/XMLSchema#',
        'pav': 'http://purl.org/pav/',
        'bibo': 'http://purl.org/ontology/bibo/',
        'oslc': 'http://open-services.net/ns/core#',
        'schema': 'http://schema.org/',
        'skos': 'http://www.w3.org/2004/02/skos/core#',
        'schema:name': {
          '@type': 'xsd:string'
        },
        'schema:description': {
          '@type': 'xsd:string'
        },
        'skos:prefLabel': {
          '@type': 'xsd:string'
        },
        'skos:altLabel': {
          '@type': 'xsd:string'
        },
        'pav:createdOn': {
          '@type': 'xsd:dateTime'
        },
        'pav:createdBy': {
          '@type': '@id'
        },
        'pav:lastUpdatedOn': {
          '@type': 'xsd:dateTime'
        },
        'oslc:modifiedBy': {
          '@type': '@id'
        }
      },
      'type': 'object',
      'title': 'phone field schema',
      'description': 'phone field schema generated by the CEDAR Template Editor 2.2.6',
      '_ui': {
        'inputType': 'phone-number'
      },
      '_valueConstraints': {
        'requiredValue': false
      },
      'properties': {
        '@type': {
          'oneOf': [
            {
              'type': 'string',
              'format': 'uri'
            },
            {
              'type': 'array',
              'minItems': 1,
              'items': {
                'type': 'string',
                'format': 'uri'
              },
              'uniqueItems': true
            }
          ]
        },
        '@value': {
          'type': [
            'string',
            'null'
          ]
        },
        'rdfs:label': {
          'type': [
            'string',
            'null'
          ]
        }
      },
      'required': [
        '@value'
      ],
      'schema:name': 'phone',
      'schema:description': 'Help Text',
      'pav:createdOn': '2019-01-30T15:43:56-0800',
      'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
      'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'schema:schemaVersion': '1.5.0',
      'additionalProperties': false,
      '@id': 'https://repo.staging.metadatacenter.org/template-fields/a9c3e553-8eb1-47a5-be2d-3938b9b1cfd4',
      '$schema': 'http://json-schema.org/draft-04/schema#'
    },
    'attribute value': {
      'type': 'array',
      'minItems': 0,
      'items': {
        '@type': 'https://schema.metadatacenter.org/core/TemplateField',
        '@context': {
          'xsd': 'http://www.w3.org/2001/XMLSchema#',
          'pav': 'http://purl.org/pav/',
          'bibo': 'http://purl.org/ontology/bibo/',
          'oslc': 'http://open-services.net/ns/core#',
          'schema': 'http://schema.org/',
          'skos': 'http://www.w3.org/2004/02/skos/core#',
          'schema:name': {
            '@type': 'xsd:string'
          },
          'schema:description': {
            '@type': 'xsd:string'
          },
          'skos:prefLabel': {
            '@type': 'xsd:string'
          },
          'skos:altLabel': {
            '@type': 'xsd:string'
          },
          'pav:createdOn': {
            '@type': 'xsd:dateTime'
          },
          'pav:createdBy': {
            '@type': '@id'
          },
          'pav:lastUpdatedOn': {
            '@type': 'xsd:dateTime'
          },
          'oslc:modifiedBy': {
            '@type': '@id'
          }
        },
        'type': 'string',
        'title': 'attribute value field schema',
        'description': 'attribute value field schema generated by the CEDAR Template Editor 2.2.6',
        '_ui': {
          'inputType': 'attribute-value'
        },
        'schema:name': 'attribute value',
        'schema:description': 'Help Text',
        'pav:createdOn': '2019-01-30T15:43:56-0800',
        'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
        'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
        'schema:schemaVersion': '1.5.0',
        'additionalProperties': false,
        '@id': 'https://repo.staging.metadatacenter.org/template-fields/3bbe020f-aaed-497a-8dee-98c349f9a8aa',
        '$schema': 'http://json-schema.org/draft-04/schema#'
      }
    },
    'list': {
      '@type': 'https://schema.metadatacenter.org/core/TemplateField',
      '@context': {
        'xsd': 'http://www.w3.org/2001/XMLSchema#',
        'pav': 'http://purl.org/pav/',
        'bibo': 'http://purl.org/ontology/bibo/',
        'oslc': 'http://open-services.net/ns/core#',
        'schema': 'http://schema.org/',
        'skos': 'http://www.w3.org/2004/02/skos/core#',
        'schema:name': {
          '@type': 'xsd:string'
        },
        'schema:description': {
          '@type': 'xsd:string'
        },
        'skos:prefLabel': {
          '@type': 'xsd:string'
        },
        'skos:altLabel': {
          '@type': 'xsd:string'
        },
        'pav:createdOn': {
          '@type': 'xsd:dateTime'
        },
        'pav:createdBy': {
          '@type': '@id'
        },
        'pav:lastUpdatedOn': {
          '@type': 'xsd:dateTime'
        },
        'oslc:modifiedBy': {
          '@type': '@id'
        }
      },
      'type': 'object',
      'title': 'list field schema',
      'description': 'list field schema generated by the CEDAR Template Editor 2.2.6',
      '_ui': {
        'inputType': 'list'
      },
      '_valueConstraints': {
        'requiredValue': false,
        'multipleChoice': false,
        'literals': [
          {
            'label': 'Untitled-0'
          },
          {
            'label': 'Untitled-1'
          }
        ]
      },
      'properties': {
        '@type': {
          'oneOf': [
            {
              'type': 'string',
              'format': 'uri'
            },
            {
              'type': 'array',
              'minItems': 1,
              'items': {
                'type': 'string',
                'format': 'uri'
              },
              'uniqueItems': true
            }
          ]
        },
        '@value': {
          'type': [
            'string',
            'null'
          ]
        },
        'rdfs:label': {
          'type': [
            'string',
            'null'
          ]
        }
      },
      'required': [
        '@value'
      ],
      'schema:name': 'list',
      'schema:description': 'Help Text',
      'pav:createdOn': '2019-01-30T15:43:56-0800',
      'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
      'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
      'schema:schemaVersion': '1.5.0',
      'additionalProperties': false,
      '@id': 'https://repo.staging.metadatacenter.org/template-fields/41262c48-c453-405e-b994-de2784c2687b',
      '$schema': 'http://json-schema.org/draft-04/schema#'
    }
  },
  'required': [
    '@context',
    '@id',
    'schema:isBasedOn',
    'schema:name',
    'schema:description',
    'pav:createdOn',
    'pav:createdBy',
    'pav:lastUpdatedOn',
    'oslc:modifiedBy',
    'text',
    'date',
    'email',
    'number',
    'link',
    'paragraph',
    'radio',
    'checkbox',
    'list',
    'phone'
  ],
  'schema:name': 'fieldtypes',
  'schema:description': '',
  'pav:createdOn': '2019-01-30T15:43:56-0800',
  'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
  'pav:lastUpdatedOn': '2019-01-30T15:43:56-0800',
  'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
  'schema:schemaVersion': '1.5.0',
  'additionalProperties': {
    'type': 'object',
    'properties': {
      '@value': {
        'type': [
          'string',
          'null'
        ]
      },
      '@type': {
        'type': 'string',
        'format': 'uri'
      }
    },
    'required': [
      '@value'
    ],
    'additionalProperties': false
  },
  'pav:version': '0.0.1',
  'bibo:status': 'bibo:draft',
  '$schema': 'http://json-schema.org/draft-04/schema#'
});
const MODEL_DATA1 = JSON.stringify({
  '@context': {
    'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
    'xsd': 'http://www.w3.org/2001/XMLSchema#',
    'pav': 'http://purl.org/pav/',
    'schema': 'http://schema.org/',
    'oslc': 'http://open-services.net/ns/core#',
    'skos': 'http://www.w3.org/2004/02/skos/core#',
    'rdfs:label': {
      '@type': 'xsd:string'
    },
    'schema:isBasedOn': {
      '@type': '@id'
    },
    'schema:name': {
      '@type': 'xsd:string'
    },
    'schema:description': {
      '@type': 'xsd:string'
    },
    'pav:createdOn': {
      '@type': 'xsd:dateTime'
    },
    'pav:createdBy': {
      '@type': '@id'
    },
    'pav:lastUpdatedOn': {
      '@type': 'xsd:dateTime'
    },
    'oslc:modifiedBy': {
      '@type': '@id'
    },
    'skos:notation': {
      '@type': 'xsd:string'
    },
    'text': 'https://schema.staging.metadatacenter.org/properties/382f3f49-bd0b-4dce-bdf5-c1c61306a639',
    'date': 'https://schema.staging.metadatacenter.org/properties/8ec1d134-2fac-4469-a12a-742f3689a821',
    'email': 'https://schema.staging.metadatacenter.org/properties/ad59e2a4-7b9a-4bb1-a4f1-e19928dc7587',
    'number': 'https://schema.staging.metadatacenter.org/properties/360c3f74-ab05-4f54-a2c9-fe7e3431d050',
    'link': 'https://schema.staging.metadatacenter.org/properties/1b049d85-956c-4913-9acb-f6a8046bd2af',
    'paragraph': 'https://schema.staging.metadatacenter.org/properties/1761d919-d82e-48e5-9b22-cee13b36c0cc',
    'radio': 'https://schema.staging.metadatacenter.org/properties/1e3cff2b-ab73-45c7-8e33-95102da99eeb',
    'checkbox': 'https://schema.staging.metadatacenter.org/properties/dfbff46a-5075-4e0c-99aa-d328197e18a7',
    'phone': 'https://schema.staging.metadatacenter.org/properties/699223a8-87d1-4942-bd22-64a18e051430',
    'list': 'https://schema.staging.metadatacenter.org/properties/5e5aa219-787d-41a7-b0bf-e360441ec00a',
    'value 1': 'https://schema.staging.metadatacenter.org/properties/41e282dd-2a08-4e17-97a9-90a0e70bf1c5',
    'value 2': 'https://schema.staging.metadatacenter.org/properties/3454eda5-696c-4edb-b7fe-5440ad1e13a1'
  },
  'text': [
    {
      '@value': 'text'
    }
  ],
  'date': [
    {
      '@value': '2019-01-11',
      '@type': 'xsd:date'
    }
  ],
  'email': {
    '@value': 'bob@company.com'
  },
  'number': {
    '@value': '66',
    '@type': 'xsd:decimal'
  },
  'link': {
    '@id': 'http://company.com'
  },
  'paragraph': {
    '@value': 'This is my very long paragraph.'
  },
  'radio': {
    '@value': 'Untitled-0'
  },
  'checkbox': [
    {
      '@value': 'Untitled-0'
    },
    {
      '@value': 'Untitled-1'
    }
  ],
  'phone': {
    '@value': '123-456-7890'
  },
  'attribute value': [
    'value 1',
    'value 2'
  ],
  'list': {
    '@value': 'Untitled-1'
  },
  'value 1': {
    '@value': '1'
  },
  'value 2': {
    '@value': '2'
  },
  'schema:isBasedOn': 'https://repo.staging.metadatacenter.org/templates/7ed749c4-7ecc-482b-b7c8-a9c5368c004b',
  'schema:name': 'fieldtypes metadata',
  'schema:description': '',
  'pav:createdOn': '2019-01-30T15:53:07-0800',
  'pav:createdBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
  'pav:lastUpdatedOn': '2019-01-30T15:53:07-0800',
  'oslc:modifiedBy': 'https://metadatacenter.org/users/bcec3d33-faf5-447a-ac96-683d8bf8c7b8',
  '@id': 'https://repo.staging.metadatacenter.org/template-instances/cdf49dee-357e-43f5-b703-8551cf2cfebd'
});
const TREE_DATA = JSON.stringify({
  'Multiple0': {
    '@type': 'element',
    '@name': 'Multiple',
    '@minItems': 0,
    '@maxItems': 10,
    '@itemCount': 0,
    'name': {
      '@type': 'textfield',
      '@name': 'Name',
      '@minItems': 0,
      '@maxItems': 2,
      key: 'name',
      subtype: 'text',
      value: {
        values: ['one', 'two'],
      },
      helpText: 'Name of project',
      hint: 'Enter the name of your project',
      required: false
    },
    'URL': {
      '@type': 'textfield',
      '@name': 'URL',
      '@minItems': 0,
      '@maxItems': 2,
      key: 'url',
      subtype: 'url',
      value: {
        values: ['', ''],
      },
      helpText: 'URL of project',
      hint: 'Enter the URL of your project',
      required: true
    },
    'pies': {
      '@type': 'dropdown',
      '@name': 'Pies',
      key: 'pies',
      value: {
        min: 1,
        max: 2,
        values: ['Rhubarb', 'Black Bottom'],
      },
      helpText: 'pie filling',
      required: false,
      options: [
        {key: 'Rhubarb', value: 'Rhubarb'},
        {key: 'Cherry', value: 'Cherry'},
        {key: 'Key Lime', value: 'Key Lime'},
        {key: 'Black Bottom', value: 'Black Bottom'}
      ],
    },
  },
  'Multiple1': {
    '@type': 'element',
    '@name': 'Multiple',
    '@maxItems': 10,
    '@minItems': 0,
    '@itemCount': 1,
    'name': {
      '@type': 'textfield',
      '@name': 'Name',
      '@minItems': 0,
      '@maxItems': 2,
      key: 'name',
      subtype: 'text',
      value: {
        values: ['one', 'two'],
      },
      helpText: 'Name of project',
      hint: 'Enter the name of your project',
      required: false
    },
    'URL': {
      '@type': 'textfield',
      '@name': 'URL',
      '@minItems': 0,
      '@maxItems': 2,
      key: 'url',
      subtype: 'url',
      value: {
        min: 1,
        max: 1,
        values: ['', ''],
      },
      helpText: 'URL of project',
      hint: 'Enter the URL of your project',
      required: true
    },
    'pies': {
      '@type': 'dropdown',
      '@name': 'Pies',
      key: 'pies',
      value: {
        min: 1,
        max: 2,
        values: ['Rhubarb', 'Black Bottom'],
      },
      helpText: 'pie filling',
      required: false,
      options: [
        {key: 'Rhubarb', value: 'Rhubarb'},
        {key: 'Cherry', value: 'Cherry'},
        {key: 'Key Lime', value: 'Key Lime'},
        {key: 'Black Bottom', value: 'Black Bottom'}
      ],
    },
  },
  'Project': {
    '@type': 'element',
    '@name': 'Project',
    'name': {
      '@type': 'textfield',
      '@name': 'Name',
      key: 'name',
      subtype: 'text',
      value: {
        values: ['one'],
      },
      helpText: 'Name of project',
      hint: 'Enter the name of your project',
      required: false
    },
    'URL': {
      '@type': 'textfield',
      '@name': 'URL',
      key: 'url',
      subtype: 'url',
      value: {
        values: [''],
      },
      helpText: 'URL of project',
      hint: 'Enter the URL of your project',
      required: true
    },
    'pies': {
      '@type': 'dropdown',
      '@name': 'Pies',
      '@minItems': 0,
      '@maxItems': 2,
      key: 'pies',
      value: {
        values: ['Rhubarb', 'Black Bottom'],
      },
      helpText: 'pie filling',
      required: false,
      options: [
        {key: 'Rhubarb', value: 'Rhubarb'},
        {key: 'Cherry', value: 'Cherry'},
        {key: 'Key Lime', value: 'Key Lime'},
        {key: 'Black Bottom', value: 'Black Bottom'}
      ],
    },
  },
  'Subjects': {
    '@type': 'element',
    '@name': 'Subjects',
    '@minItems': 0,
    '@maxItems': 2,
    '@itemCount': 0,
    'date': {
      '@type': 'date',
      '@name': 'Date',
      '@minItems': 0,
      '@maxItems': 2,
      key: 'date',
      subtype: 'date',
      value: {
        values: ['5/22/87', '8/17/85'],
      },
      helpText: 'start date',
      required: false,
      hint: 'Enter the start date of the project'
    },
    'status': {
      '@type': 'radio',
      '@name': 'Status',
      '@minItems': 0,
      '@maxItems': 2,
      subtype: 'radio',
      key: 'status',
      value: {
        values: [0, 3],
      },
      required: false,
      helpText: 'status of project',
      hint: 'begin',
      options: [
        {label: 'begin', value: 0},
        {label: 'start', value: 1},
        {label: 'middle', value: 2},
        {label: 'finish', value: 3}
      ],
    },
    'organism': {
      '@type': 'textfield',
      '@name': 'Organism',
      subtype: 'text',
      key: 'organism',
      value: {
        values: [''],
      },
      required: false,
      helpText: 'The organism on which your experiment acted',
      hint: 'e.g. human'
    }
  },
  'Experiments': {
    '@type': 'element',
    '@name': 'Experiments',
    'description': {
      '@type': 'paragraph',
      '@name': 'Description',
      '@minItems': 0,
      '@maxItems': 2,
      key: 'description',
      value: {
        values: ['', ''],
      },
      helpText: 'Description of project',
      hint: 'Enter the description of your project',
      required: true
    },
    'runs': {
      '@type': 'textfield',
      '@name': 'Run count',
      '@minItems': 0,
      '@maxItems': 2,
      subtype: 'number',
      key: 'runs',
      value: {
        values: ['', ''],
      },
      helpText: 'The number of experimental runs from 4 to 10',
      required: true,
      hint: 'e.g. 5',
      min: 4,
      max: 10
    },
    'contact': {
      '@type': 'element',
      '@name': 'Contact',
      'firstname': {
        '@type': 'textfield',
        '@name': 'First name',
        '@minItems': 0,
        '@maxItems': 1,
        subtype: 'text',
        key: 'first name',
        value: {
          values: [''],
        },
        required: false,
        helpText: 'The first name of your contact'
      },
      'lasttname': {
        '@type': 'textfield',
        '@name': 'Last name',
        subtype: 'text',
        key: 'last name',
        value: {
          values: [''],
        },
        required: false,
        helpText: 'The last name of your contact'
      },
      'email': {
        '@type': 'textfield',
        '@name': 'Email',
        '@minItems': 0,
        '@maxItems': 2,
        subtype: 'email',
        key: 'email',
        value: {
          values: ['', ''],
        },
        helpText: 'Email of contact',
        hint: 'Enter the email address for your contact',
        required: true
      },
      'phone': {
        '@type': 'textfield',
        '@name': 'Phone',
        subtype: 'tel',
        key: 'phone',
        value: {
          values: [''],
        },
        hint: 'e.g. 555-555-1212',
        required: false,
        helpText: 'The phone number of your contact'
      },
      'context': {
        '@type': 'textfield',
        '@name': 'Context',
        subtype: 'text',
        key: 'context',
        value: {
          values: [''],
        },
        required: false,
        helpText: 'The context of your project',
        hint: 'e.g. NCI'
      },
      'classification': {
        '@type': 'textfield',
        '@name': 'Classification',
        subtype: 'text',
        key: 'classification',
        value: {
          values: [''],
        },
        required: false,
        helpText: 'The classification of your project',
        hint: 'e.g. Cancer'
      },
      'address': {
        '@type': 'element',
        '@name': 'Address',
        'phone': {
          '@type': 'textfield',
          '@name': 'Phone',
          subtype: 'tel',
          key: 'phone',
          value: {
            values: [''],
          },
          hint: 'e.g. 555-555-1212',
          required: false,
          helpText: 'The phone number of your contact'
        },
        'context': {
          '@type': 'textfield',
          '@name': 'Context',
          subtype: 'text',
          key: 'context',
          value: {
            values: [''],
          },
          required: false,
          helpText: 'The context of your project',
          hint: 'e.g. NCI'
        },
      }
    },
    'goal': {
      '@type': 'checkbox',
      '@name': 'Goal',
      '@minItems': 0,
      '@maxItems': 1,
      key: 'goal',
      subtype: 'checkbox',
      value: {
        values: [[true, false, true, false], [false, false, true, true]],
      },
      required: false,
      options: [
        {key: 'initial', label: 'initial'},
        {key: 'in process', label: 'in process'},
        {key: 'in committee', label: 'in committee'},
        {key: 'complete', label: 'complete'}
      ],
    }
  }
});

@Injectable()
export class TemplateData {

  public templateData: object[];
  public modelData: object[];
  public treeData: object;

  constructor() {

    this.templateData = [];
    this.templateData.push(JSON.parse(TEMPLATE_DATA));
    this.templateData.push(JSON.parse(TEMPLATE_DATA1));

    this.modelData = [];
    this.modelData.push(JSON.parse(MODEL_DATA));
    this.modelData.push(JSON.parse(MODEL_DATA1));

    this.treeData = JSON.parse(TREE_DATA);
  }
}
