import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TemplateService {
  form: object;
  const: object;

  constructor() {
    this.form = {
      "@id": "https://repo.metadatacenter.orgx/templates/f3ec755d-b0f7-4dd7-83c5-fbccc83c50b9",
      "@type": "https://schema.metadatacenter.org/core/Template",
      "@context": {
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "pav": "http://purl.org/pav/",
        "bibo": "http://purl.org/ontology/bibo/",
        "oslc": "http://open-services.net/ns/core#",
        "schema": "http://schema.org/",
        "schema:name": {
          "@type": "xsd:string"
        },
        "schema:description": {
          "@type": "xsd:string"
        },
        "pav:createdOn": {
          "@type": "xsd:dateTime"
        },
        "pav:createdBy": {
          "@type": "@id"
        },
        "pav:lastUpdatedOn": {
          "@type": "xsd:dateTime"
        },
        "oslc:modifiedBy": {
          "@type": "@id"
        }
      },
      "type": "object",
      "title": "First template template schema",
      "description": "First template template schema generated by the CEDAR Template Editor 2.1.12-SNAPSHOT",
      "_ui": {
        "pages": [],
        "order": [
          "first field"
        ],
        "propertyLabels": {
          "first field": "first field"
        },
        "propertyDescriptions": {
          "first field": "Help Text"
        }
      },
      "properties": {
        "@context": {
          "type": "object",
          "properties": {
            "rdfs": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://www.w3.org/2000/01/rdf-schema#"
              ]
            },
            "xsd": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://www.w3.org/2001/XMLSchema#"
              ]
            },
            "pav": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://purl.org/pav/"
              ]
            },
            "schema": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://schema.org/"
              ]
            },
            "oslc": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://open-services.net/ns/core#"
              ]
            },
            "skos": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://www.w3.org/2004/02/skos/core#"
              ]
            },
            "rdfs:label": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:string"
                  ]
                }
              }
            },
            "schema:isBasedOn": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "@id"
                  ]
                }
              }
            },
            "schema:name": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:string"
                  ]
                }
              }
            },
            "schema:description": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:string"
                  ]
                }
              }
            },
            "pav:createdOn": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:dateTime"
                  ]
                }
              }
            },
            "pav:createdBy": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "@id"
                  ]
                }
              }
            },
            "pav:lastUpdatedOn": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:dateTime"
                  ]
                }
              }
            },
            "oslc:modifiedBy": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "@id"
                  ]
                }
              }
            },
            "skos:notation": {
              "type": "object",
              "properties": {
                "@type": {
                  "type": "string",
                  "enum": [
                    "xsd:string"
                  ]
                }
              }
            },
            "first field": {
              "enum": [
                "https://schema.metadatacenter.orgx/properties/67049184-30db-4292-8283-c010470d44fd"
              ]
            }
          },
          "required": [
            "xsd",
            "pav",
            "schema",
            "oslc",
            "schema:isBasedOn",
            "schema:name",
            "schema:description",
            "pav:createdOn",
            "pav:createdBy",
            "pav:lastUpdatedOn",
            "oslc:modifiedBy"
          ],
          "additionalProperties": false
        },
        "@id": {
          "type": "string",
          "format": "uri"
        },
        "@type": {
          "oneOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "format": "uri"
              },
              "uniqueItems": true
            }
          ]
        },
        "schema:isBasedOn": {
          "type": "string",
          "format": "uri"
        },
        "schema:name": {
          "type": "string",
          "minLength": 1
        },
        "schema:description": {
          "type": "string"
        },
        "pav:createdOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "pav:createdBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "pav:lastUpdatedOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "oslc:modifiedBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "first field": {
          "@type": "https://schema.metadatacenter.org/core/TemplateField",
          "@context": {
            "xsd": "http://www.w3.org/2001/XMLSchema#",
            "pav": "http://purl.org/pav/",
            "bibo": "http://purl.org/ontology/bibo/",
            "oslc": "http://open-services.net/ns/core#",
            "schema": "http://schema.org/",
            "skos": "http://www.w3.org/2004/02/skos/core#",
            "schema:name": {
              "@type": "xsd:string"
            },
            "schema:description": {
              "@type": "xsd:string"
            },
            "skos:prefLabel": {
              "@type": "xsd:string"
            },
            "skos:altLabel": {
              "@type": "xsd:string"
            },
            "pav:createdOn": {
              "@type": "xsd:dateTime"
            },
            "pav:createdBy": {
              "@type": "@id"
            },
            "pav:lastUpdatedOn": {
              "@type": "xsd:dateTime"
            },
            "oslc:modifiedBy": {
              "@type": "@id"
            }
          },
          "type": "object",
          "title": "first field field schema",
          "description": "first field field schema generated by the CEDAR Template Editor 2.1.12-SNAPSHOT",
          "_ui": {
            "inputType": "textfield"
          },
          "_valueConstraints": {
            "requiredValue": false
          },
          "properties": {
            "@type": {
              "oneOf": [
                {
                  "type": "string",
                  "format": "uri"
                },
                {
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "type": "string",
                    "format": "uri"
                  },
                  "uniqueItems": true
                }
              ]
            },
            "@value": {
              "type": [
                "string",
                "null"
              ]
            },
            "rdfs:label": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "@value"
          ],
          "schema:name": "first field",
          "schema:description": "Help Text",
          "pav:createdOn": "2018-11-27T13:23:00-0800",
          "pav:createdBy": "https://metadatacenter.org/users/d39cf7ae-3d7a-4eb5-9669-f57e2ac02423",
          "pav:lastUpdatedOn": "2018-11-27T13:23:00-0800",
          "oslc:modifiedBy": "https://metadatacenter.org/users/d39cf7ae-3d7a-4eb5-9669-f57e2ac02423",
          "schema:schemaVersion": "1.5.0",
          "additionalProperties": false,
          "@id": "https://repo.metadatacenter.orgx/template-fields/b6a77a89-fadd-4ed6-b3b5-5e70fb053c6b",
          "$schema": "http://json-schema.org/draft-04/schema#"
        }
      },
      "required": [
        "@context",
        "@id",
        "schema:isBasedOn",
        "schema:name",
        "schema:description",
        "pav:createdOn",
        "pav:createdBy",
        "pav:lastUpdatedOn",
        "oslc:modifiedBy",
        "first field"
      ],
      "schema:name": "first template",
      "schema:description": "",
      "pav:createdOn": "2018-11-27T13:23:00-0800",
      "pav:createdBy": "https://metadatacenter.org/users/d39cf7ae-3d7a-4eb5-9669-f57e2ac02423",
      "pav:lastUpdatedOn": "2018-11-27T13:23:00-0800",
      "oslc:modifiedBy": "https://metadatacenter.org/users/d39cf7ae-3d7a-4eb5-9669-f57e2ac02423",
      "schema:schemaVersion": "1.5.0",
      "additionalProperties": false,
      "pav:version": "0.0.1",
      "bibo:status": "bibo:draft",
      "$schema": "http://json-schema.org/draft-04/schema#"
    };
    this.const =   {
      "resourceType" : {
        "TEMPLATE": "template",
        "FIELD"   : "field",
        "ELEMENT" : "element",
        "INSTANCE": "instance",
        "LINK"    : "link",
        "FOLDER"  : "folder",
        "METADATA": "metadata",
      },
      "publication"  : {
        "VERSION"  : "pav:version",
        "STATUS"   : "bibo:status",
        "DRAFT"    : "bibo:draft",
        "PUBLISHED": "bibo:published",
        "ALL"      : "all",
        "LATEST"   : "latest-by-status"
      },
      "model"        : {
        "NAME"               : "schema:name",
        "DESCRIPTION"        : "schema:description",
        "IDENTIFIER"         : "schema:identifier",
        "ISBASEDON"          : "schema:isBasedOn",
        "NUMBEROFINSTANCES"  : 'numberOfInstances',
        "DERIVEDFROM"        : "derivedFrom",
        "PREFLABEL"          : "skos:prefLabel",
        "CONSTRAINEDTERMID"  : 'termUri',
        "CONSTRAINEDID"      : '@id',
        "CONSTRAINEDLABEL"   : 'rdfs:label',
        "CONSTRAINEDNOTATION": 'skos:notation',
        "NOTATION"           : 'notation'
      },
      "dateFormats"  : {
        "ar-SA"      : "dd/MM/yy",
        "bg-BG"      : "dd.M.yyyy",
        "ca-ES"      : "dd/MM/yyyy",
        "zh-TW"      : "yyyy/M/d",
        "cs-CZ"      : "d.M.yyyy",
        "da-DK"      : "dd-MM-yyyy",
        "de-DE"      : "dd.MM.yyyy",
        "el-GR"      : "d/M/yyyy",
        "en-US"      : "M/d/yyyy",
        "fi-FI"      : "d.M.yyyy",
        "fr-FR"      : "dd/MM/yyyy",
        "he-IL"      : "dd/MM/yyyy",
        "hu-HU"      : "yyyy. MM. dd.",
        "is-IS"      : "d.M.yyyy",
        "it-IT"      : "dd/MM/yyyy",
        "ja-JP"      : "yyyy/MM/dd",
        "ko-KR"      : "yyyy-MM-dd",
        "nl-NL"      : "d-M-yyyy",
        "nb-NO"      : "dd.MM.yyyy",
        "pl-PL"      : "yyyy-MM-dd",
        "pt-BR"      : "d/M/yyyy",
        "ro-RO"      : "dd.MM.yyyy",
        "ru-RU"      : "dd.MM.yyyy",
        "hr-HR"      : "d.M.yyyy",
        "sk-SK"      : "d. M. yyyy",
        "sq-AL"      : "yyyy-MM-dd",
        "sv-SE"      : "yyyy-MM-dd",
        "th-TH"      : "d/M/yyyy",
        "tr-TR"      : "dd.MM.yyyy",
        "ur-PK"      : "dd/MM/yyyy",
        "id-ID"      : "dd/MM/yyyy",
        "uk-UA"      : "dd.MM.yyyy",
        "be-BY"      : "dd.MM.yyyy",
        "sl-SI"      : "d.M.yyyy",
        "et-EE"      : "d.MM.yyyy",
        "lv-LV"      : "yyyy.MM.dd.",
        "lt-LT"      : "yyyy.MM.dd",
        "fa-IR"      : "MM/dd/yyyy",
        "vi-VN"      : "dd/MM/yyyy",
        "hy-AM"      : "dd.MM.yyyy",
        "az-Latn-AZ" : "dd.MM.yyyy",
        "eu-ES"      : "yyyy/MM/dd",
        "mk-MK"      : "dd.MM.yyyy",
        "af-ZA"      : "yyyy/MM/dd",
        "ka-GE"      : "dd.MM.yyyy",
        "fo-FO"      : "dd-MM-yyyy",
        "hi-IN"      : "dd-MM-yyyy",
        "ms-MY"      : "dd/MM/yyyy",
        "kk-KZ"      : "dd.MM.yyyy",
        "ky-KG"      : "dd.MM.yy",
        "sw-KE"      : "M/d/yyyy",
        "uz-Latn-UZ" : "dd/MM yyyy",
        "tt-RU"      : "dd.MM.yyyy",
        "pa-IN"      : "dd-MM-yy",
        "gu-IN"      : "dd-MM-yy",
        "ta-IN"      : "dd-MM-yyyy",
        "te-IN"      : "dd-MM-yy",
        "kn-IN"      : "dd-MM-yy",
        "mr-IN"      : "dd-MM-yyyy",
        "sa-IN"      : "dd-MM-yyyy",
        "mn-MN"      : "yy.MM.dd",
        "gl-ES"      : "dd/MM/yy",
        "kok-IN"     : "dd-MM-yyyy",
        "syr-SY"     : "dd/MM/yyyy",
        "dv-MV"      : "dd/MM/yy",
        "ar-IQ"      : "dd/MM/yyyy",
        "zh-CN"      : "yyyy/M/d",
        "de-CH"      : "dd.MM.yyyy",
        "en-GB"      : "dd/MM/yyyy",
        "es-MX"      : "dd/MM/yyyy",
        "fr-BE"      : "d/MM/yyyy",
        "it-CH"      : "dd.MM.yyyy",
        "nl-BE"      : "d/MM/yyyy",
        "nn-NO"      : "dd.MM.yyyy",
        "pt-PT"      : "dd-MM-yyyy",
        "sr-Latn-CS" : "d.M.yyyy",
        "sv-FI"      : "d.M.yyyy",
        "az-Cyrl-AZ" : "dd.MM.yyyy",
        "ms-BN"      : "dd/MM/yyyy",
        "uz-Cyrl-UZ" : "dd.MM.yyyy",
        "ar-EG"      : "dd/MM/yyyy",
        "zh-HK"      : "d/M/yyyy",
        "de-AT"      : "dd.MM.yyyy",
        "en-AU"      : "d/MM/yyyy",
        "es-ES"      : "dd/MM/yyyy",
        "fr-CA"      : "yyyy-MM-dd",
        "sr-Cyrl-CS" : "d.M.yyyy",
        "ar-LY"      : "dd/MM/yyyy",
        "zh-SG"      : "d/M/yyyy",
        "de-LU"      : "dd.MM.yyyy",
        "en-CA"      : "dd/MM/yyyy",
        "es-GT"      : "dd/MM/yyyy",
        "fr-CH"      : "dd.MM.yyyy",
        "ar-DZ"      : "dd-MM-yyyy",
        "zh-MO"      : "d/M/yyyy",
        "de-LI"      : "dd.MM.yyyy",
        "en-NZ"      : "d/MM/yyyy",
        "es-CR"      : "dd/MM/yyyy",
        "fr-LU"      : "dd/MM/yyyy",
        "ar-MA"      : "dd-MM-yyyy",
        "en-IE"      : "dd/MM/yyyy",
        "es-PA"      : "MM/dd/yyyy",
        "fr-MC"      : "dd/MM/yyyy",
        "ar-TN"      : "dd-MM-yyyy",
        "en-ZA"      : "yyyy/MM/dd",
        "es-DO"      : "dd/MM/yyyy",
        "ar-OM"      : "dd/MM/yyyy",
        "en-JM"      : "dd/MM/yyyy",
        "es-VE"      : "dd/MM/yyyy",
        "ar-YE"      : "dd/MM/yyyy",
        "en-029"     : "MM/dd/yyyy",
        "es-CO"      : "dd/MM/yyyy",
        "ar-SY"      : "dd/MM/yyyy",
        "en-BZ"      : "dd/MM/yyyy",
        "es-PE"      : "dd/MM/yyyy",
        "ar-JO"      : "dd/MM/yyyy",
        "en-TT"      : "dd/MM/yyyy",
        "es-AR"      : "dd/MM/yyyy",
        "ar-LB"      : "dd/MM/yyyy",
        "en-ZW"      : "M/d/yyyy",
        "es-EC"      : "dd/MM/yyyy",
        "ar-KW"      : "dd/MM/yyyy",
        "en-PH"      : "M/d/yyyy",
        "es-CL"      : "dd-MM-yyyy",
        "ar-AE"      : "dd/MM/yyyy",
        "es-UY"      : "dd/MM/yyyy",
        "ar-BH"      : "dd/MM/yyyy",
        "es-PY"      : "dd/MM/yyyy",
        "ar-QA"      : "dd/MM/yyyy",
        "es-BO"      : "dd/MM/yyyy",
        "es-SV"      : "dd/MM/yyyy",
        "es-HN"      : "dd/MM/yyyy",
        "es-NI"      : "dd/MM/yyyy",
        "es-PR"      : "dd/MM/yyyy",
        "am-ET"      : "d/M/yyyy",
        "tzm-Latn-DZ": "dd-MM-yyyy",
        "iu-Latn-CA" : "d/MM/yyyy",
        "sma-NO"     : "dd.MM.yyyy",
        "mn-Mong-CN" : "yyyy/M/d",
        "gd-GB"      : "dd/MM/yyyy",
        "en-MY"      : "d/M/yyyy",
        "prs-AF"     : "dd/MM/yy",
        "bn-BD"      : "dd-MM-yy",
        "wo-SN"      : "dd/MM/yyyy",
        "rw-RW"      : "M/d/yyyy",
        "qut-GT"     : "dd/MM/yyyy",
        "sah-RU"     : "MM.dd.yyyy",
        "gsw-FR"     : "dd/MM/yyyy",
        "co-FR"      : "dd/MM/yyyy",
        "oc-FR"      : "dd/MM/yyyy",
        "mi-NZ"      : "dd/MM/yyyy",
        "ga-IE"      : "dd/MM/yyyy",
        "se-SE"      : "yyyy-MM-dd",
        "br-FR"      : "dd/MM/yyyy",
        "smn-FI"     : "d.M.yyyy",
        "moh-CA"     : "M/d/yyyy",
        "arn-CL"     : "dd-MM-yyyy",
        "ii-CN"      : "yyyy/M/d",
        "dsb-DE"     : "d. M. yyyy",
        "ig-NG"      : "d/M/yyyy",
        "kl-GL"      : "dd-MM-yyyy",
        "lb-LU"      : "dd/MM/yyyy",
        "ba-RU"      : "dd.MM.yy",
        "nso-ZA"     : "yyyy/MM/dd",
        "quz-BO"     : "dd/MM/yyyy",
        "yo-NG"      : "d/M/yyyy",
        "ha-Latn-NG" : "d/M/yyyy",
        "fil-PH"     : "M/d/yyyy",
        "ps-AF"      : "dd/MM/yy",
        "fy-NL"      : "d-M-yyyy",
        "ne-NP"      : "M/d/yyyy",
        "se-NO"      : "dd.MM.yyyy",
        "iu-Cans-CA" : "d/M/yyyy",
        "sr-Latn-RS" : "d.M.yyyy",
        "si-LK"      : "yyyy-MM-dd",
        "sr-Cyrl-RS" : "d.M.yyyy",
        "lo-LA"      : "dd/MM/yyyy",
        "km-KH"      : "yyyy-MM-dd",
        "cy-GB"      : "dd/MM/yyyy",
        "bo-CN"      : "yyyy/M/d",
        "sms-FI"     : "d.M.yyyy",
        "as-IN"      : "dd-MM-yyyy",
        "ml-IN"      : "dd-MM-yy",
        "en-IN"      : "dd-MM-yyyy",
        "or-IN"      : "dd-MM-yy",
        "bn-IN"      : "dd-MM-yy",
        "tk-TM"      : "dd.MM.yy",
        "bs-Latn-BA" : "d.M.yyyy",
        "mt-MT"      : "dd/MM/yyyy",
        "sr-Cyrl-ME" : "d.M.yyyy",
        "se-FI"      : "d.M.yyyy",
        "zu-ZA"      : "yyyy/MM/dd",
        "xh-ZA"      : "yyyy/MM/dd",
        "tn-ZA"      : "yyyy/MM/dd",
        "hsb-DE"     : "d. M. yyyy",
        "bs-Cyrl-BA" : "d.M.yyyy",
        "tg-Cyrl-TJ" : "dd.MM.yy",
        "sr-Latn-BA" : "d.M.yyyy",
        "smj-NO"     : "dd.MM.yyyy",
        "rm-CH"      : "dd/MM/yyyy",
        "smj-SE"     : "yyyy-MM-dd",
        "quz-EC"     : "dd/MM/yyyy",
        "quz-PE"     : "dd/MM/yyyy",
        "hr-BA"      : "d.M.yyyy.",
        "sr-Latn-ME" : "d.M.yyyy",
        "sma-SE"     : "yyyy-MM-dd",
        "en-SG"      : "d/M/yyyy",
        "ug-CN"      : "yyyy-M-d",
        "sr-Cyrl-BA" : "d.M.yyyy",
        "es-US"      : "M/d/yyyy"
      }
    };
  }

  getTemplate()
  {
    return this.form;
  }
}
